### YamlMime:FAQ
metadata:
  title: 一元展開に関する FAQ
  f1.keywords:
  - NOCSH
  ms.author: kwekua
  author: kwekua
  manager: scotv
  audience: Admin
  ms.topic: article
  ms.service: o365-administration
  localization_priority: Normal
  ms.collection:
  - M365-subscription-management
  - Adm_O365
  - Adm_NonTOC
  ms.custom: AdminSurgePortfolio
  search.appverid:
  - BCS160
  - MET150
  - MOE150
  description: 一元的な展開に関するよくある質問に対する回答を、Microsoft 365 管理センター。
  ms.openlocfilehash: aace2db69a50f574ac6d48c95496ff65a535d150
  ms.sourcegitcommit: a0185d6b0dd091db6e1e1bfae2f68ab0e3cf05e5
  ms.translationtype: MT
  ms.contentlocale: ja-JP
  ms.lasthandoff: 08/13/2021
  ms.locfileid: "58254888"
title: 一元展開に関する FAQ
summary: Office 365 管理者が組織内のユーザーとグループに Office アドイン (Word、Excel、PowerPoint、および Outlook) を展開する場合は、この記事で説明した集中展開を使用するためのすべての要件を満たしている場合に、集中展開が推奨されます。
sections:
- name: 無視
  questions:
  - question: >
      How do I know if my organization is set up for Centralized Deployment?
    answer: "Centralized deployment of add-ins requires that users are using Microsoft 365 Apps for enterprise (and are signed into Office using their organizational log-in credentials) and have Exchange Online mailboxes. Your subscription directory must either be in, or federated to, Azure Active Directory. \n \nCentralized Deployment is only supported for online mailboxes. It does not support deployment to on-premises Exchange mailboxes.\n\nYou can use the [Centralized Deployment Compatibility Checker](centralized-deployment-of-add-ins.md#centralized-deployment-compatibility-checker) to determine if your subscription is eligible. \n  \n"
  - question: >
      How do you target add-in user assignments with Centralized Deployment?
    answer: "Centralized Deployment supports assignments to individual users, groups, and everyone in the tenant. Centralized Deployment can be used for users in top-level groups or groups without parent groups, but not for users in nested groups or groups that have parent groups. Centralized Deployment is also part of most Azure Active Directory groups, including Office 365 Groups, distribution lists, and security groups. \n\nIt is better to use groups assignments instead of individual user assignment for easier management.\n \nFor more details, see [User and Group assignments](./centralized-deployment-of-add-ins.md?view=o365-worldwide#user-and-group-assignments).\n \n"
  - question: "How long does it take for add-ins to show up for all users? \n"
    answer: "It can take up to 24 hours for an add-in to show up for all users. It can take the same amount of time for add-in updates, changes from turn on or turn off, or add-in removals. \n"
  - question: >
      As an administrator, how do I manage the user access to add-ins for my organization?
    answer: >
      For easy deployment of add-ins to users, groups, or to your entire organization, we recommend administrators use Centralized Deployment.


      For more information about managing user access, see:
       - [Prevent add-in downloads by turning off the Office Store across all clients (Except Outlook)](./manage-addins-in-the-admin-center.md#prevent-add-in-downloads-by-turning-off-the-office-store-across-all-clients-except-outlook)
       - [Specify the administrators and users who can install and manage add-ins for Outlook](/Exchange/specify-who-can-install-and-manage-add-ins-2013-help)
  - question: "Will Centralized Deployment provide admins the flexibility to choose the deployment method for Outlook add-ins? \n"
    answer: "Yes. Centralized Deployment provides admins the flexibility to choose one of three deployment methods for Outlook add-ins during add-in deployment:\n\n**Fixed (Default)** \nThe add-in is deployed automatically to the assigned users, and they cannot remove it.\n \n**Available**\nUsers can install the add-in in Outlook by choosing **Home > Get More add-ins > Admin-managed**.\n \n**Optional**\nThe add-in is deployed automatically to the assigned users, but they can choose to remove it.\n    \n"
  - question: "Can admins update Line-of-Business (LOB) add-ins? \n"
    answer: "Yes. Admins can upload a new manifest file to support metadata changes for admin-deployed LOB add-ins. The add-in updates the next time the Office applications starts. The web application can change at any time.\n \nFor more information, see [line-of-business add-in](./manage-addins-in-the-admin-center.md).  \n"
  - question: "Can admins turn off add-ins? \n"
    answer: >
      Yes. Admins can turn on or off the add-ins they deploy for all users from the Microsoft admin center.


      For more information, see [Add-in states](./manage-addins-in-the-admin-center.md#add-in-states).
  - question: >
      Can admins delete or remove add-ins?
    answer: "Yes. Admins can delete add-ins they deployed for all users from the Microsoft admin center.\n\nFor more information, see [Delete an add-in](./manage-addins-in-the-admin-center.md#delete-an-add-in). \n  \n"
  - question: "Can admins deploy paid add-ins from the Office Store using Centralized Deployment? \n"
    answer: "No. You can't deploy paid add-ins from the Office Store using Centralized Deployment at this time. \n \nWe suggest reaching out to the ISV Developer for the paid add-in to request a manifest file or a URL. The tenant admin can then deploy the add-in as a LOB add-in using Centralized Deployment.\n   \n"
  - question: "Which admin role do I need to manage add-ins for my organization? \n"
    answer: "Global Admin is the recommended role with complete access to add-in management lifecycle. If you're the person who purchased your Microsoft 365 Business subscription, you are the Global admin.\n\nYour subscription comes with a set of admin roles that you can assign to other users in your organization. Each admin role maps to common business functions and gives people in your organization permissions to perform specific tasks in the Microsoft 365 admin center.  \n \nFor more information, see [Assign admin roles](../add-users/assign-admin-roles.md?view=o365-worldwide)."
